language: node_js
node_js:
- stable
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env: CXX=g++-4.8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
